### ISSUE TITLE
Non-AppImage build fails to start with exit code 255

### ISSUE THREAD

**Issue by jplatte** [minecraft-linux/mcpelauncher-ui-qt#34]
It doesn't print anything to `stdout` or `stderr`. I installed it through the [`mcpelauncher-ui-git`](https://aur.archlinux.org/packages/mcpelauncher-ui-git) AUR package (today).

**Comment by ChristopherHX** [comment]
Some bad gpu drivers spam the console, this was considered a bug so the logging has been hidded behind `-v` the verbose flag.

There are many reasons qt cannot start, missing qml modules etc.

Use the cli flag `-v` and look/post the qt error, I'm not even use arch

**Comment by jplatte** [comment]
Thanks! Turns out my environment variable `QT_STYLE_OVERRIDE` was causing issues (and not working anyways, seems like adwaita-qt project is no longer maintained 😢).

This was the error:

```
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml: module "adwaita" is not installed
```

and it was fixed by simply unsetting the environment variable.

Other apps like keepassxc just logged

```
QApplication: invalid style override 'adwaita' passed, ignoring it.
```

and ran fine, but I supposed this likely not due to your code but something QML-related.
