### ISSUE TITLE
Ability to use custom version DB

### ISSUE THREAD

**Issue by sorenbug** [minecraft-linux/mcpelauncher-ui-qt#4]
If players have made a pull request to the versiondb that has not been merged yet, they should be able to provide the option to play on that versiondb and use those versions.

**Comment by MCMrARM** [comment]
Even if they made that PR, the launcher would crash on startup, so I believe it does not make sense.

**Comment by MCMrARM** [comment]
Oh you are referring to this: https://github.com/minecraft-linux/mcpelauncher-versiondb/pull/1
Blame me, my bot was down and I was away. This shouldn't happen again.

**Comment by sorenbug** [comment]
I would personally suggest adding a description to that repo along the
lines of `[DO NOT PR] Automatically generated version info for Minecraft
Pocket Edition.` so people like me don't come along during another
situation like this 😅

**Comment by MCMrARM** [comment]
I don't think this situation will arise again any time soon, so it shouldn't be required. Added the description for the repo though.
